language: php

php:
    - "7.2"
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

sudo: false

git:
    submodules: false

before_script:
    - make install check

script:
    - make test


services:
  - mysql


before_install:
- mysql -u root --password="" < test/travis.sql
- mysql -u user --password="pass" < sql/ddl/ddl.sql
- mysql -u user --password="pass" < sql/ddl/insert.sql

# notifications:
#     irc: "irc.freenode.org#dbwebb"
#     urls:
        # # canax
        # - https://webhooks.gitter.im/e/6e4660b0024de67de0af
        # # canax/commons
        # - https://webhooks.gitter.im/e/dd6775c1f5b11b7421da
#     on_success: change  # options: [always|never|change] default: always
#     on_failure: always  # options: [always|never|change] default: always
#     on_start: never     # options: [always|never|change] default: always
