language: php

php:
    - "7.2"


sudo: false

git:
    submodules: false

before_script:
    - make install check

script:
    - make test

services:
  - mysql

before_install:
  - mysql -u root --password="" < test/travis.sql
