version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            #- image: circleci/php:7.1.5-browsers
            - image: anax/dev
            environment:
                MYSQL_HOST: 127.0.0.1
                MYSQL_DB: travel
                MYSQL_USER: root
                MYSQL_ALLOW_EMPTY_PASSWORD: true
                MYSQL_PASSWORD:
          - image: mysql:5.7
            command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
            environment:
                MYSQL_USER: root
                MYSQL_ALLOW_EMPTY_PASSWORD: true

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/mysql:9.4

        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "composer.json" }}
                    # fallback to using the latest cache if no exact match
                    # is found
                    - v1-dependencies-

            #- run: composer install -n --prefer-dist
            - run: sudo apt install -y mysql-client
            - run:
                name: Mysql database
                command: mysql  -h 127.0.0.1 -u root -e "create database travel;"
            - run: make install
            - run: ./install.bash

            - save_cache:
                paths:
                    - ./vendor
                key: v1-dependencies-{{ checksum "composer.json" }}

            - run: make check
            - run: make test



# notify:
#     webhooks:
#         # canax
#         - url: https://webhooks.gitter.im/e/c8ff44f50de935adf880
#         # canax/commons
#         - url: https://webhooks.gitter.im/e/7a5e4ea6070af520503c
